import{S as c,i as a}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();async function l(s){const r=`https://pixabay.com/api/?key=49484019-11a5d61f6cd196bafa2004bf7&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true`;try{const n=await fetch(r);if(!n.ok)throw new Error("Failed to fetch images");return await n.json()}catch(n){return console.error(n),{hits:[]}}}function f(s){const o=document.querySelector(".gallery");o.innerHTML=s.map(r=>`
        <a href="${r.largeImageURL}" class="gallery-item">
            <img src="${r.webformatURL}" alt="${r.tags}">
            <div class="info">
                <p>❤️ ${r.likes}  👁️ ${r.views}  💬 ${r.comments}  ⬇️ ${r.downloads}</p>
            </div>
        </a>
    `).join(""),new c(".gallery a").refresh()}document.querySelector("#search-form").addEventListener("submit",async s=>{s.preventDefault(),console.log("submit"),console.log(s);const o=s.target.elements[0].value.trim();if(!o){a.warning({title:"Warning",message:"Enter a search term!"});return}document.querySelector(".gallery").innerHTML='<div class="loader"></div>';const{hits:r}=await l(o);r.length===0?a.error({title:"Error",message:"No images found!"}):f(r)});
//# sourceMappingURL=index.js.map
